/**
 * Contract wording, per locale (Plan §7, §6.2).
 *
 * Kept out of the service because it is prose a lawyer may want to review and
 * revise without touching generation logic, and because a clause list is the
 * part of a contract that must be diffable.
 *
 * **Farsi maps to English on purpose.** The embedded font has Arabic glyphs,
 * but pdf-lib has no shaping engine, so Farsi would render as disconnected
 * letters in the wrong order — worse than English in a document someone signs.
 * `NOT_IN_YOUR_LANGUAGE` says so in the document itself rather than leaving a
 * reader to wonder. See the note in pdf.service.ts.
 */
export type ContractLocale = 'en' | 'tr' | 'ru';

/** The locales a contract can actually be rendered in. */
export const CONTRACT_LOCALES: ContractLocale[] = ['en', 'tr', 'ru'];

export function contractLocale(userLocale: string | null | undefined): ContractLocale {
  return (CONTRACT_LOCALES as string[]).includes(userLocale ?? '')
    ? (userLocale as ContractLocale)
    : 'en';
}

/**
 * Shown when the reader's own language is not one a contract can render in.
 *
 * Written in English rather than the reader's language, which looks backwards
 * until you notice the circularity: the reason for the notice is that we cannot
 * draw that script, so a notice in it would be stripped to nothing. Naming the
 * language in English is the most that can actually reach the page.
 */
export const NOT_IN_YOUR_LANGUAGE: Record<string, string> = {
  fa: 'NOTE: This document is issued in English. A Farsi version is not yet available — please obtain a certified translation before signing if you need one.',
};

interface Clause {
  heading: string;
  body: string;
}

export interface ContractCopy {
  tenancyTitle: string;
  mandateTitle: string;
  reference: (id: string) => string;
  intro: string;
  mandateIntro: string;
  footer: string;
  labels: Record<string, string>;
  /** Units belong with the number and have to translate with it. */
  months: (n: number) => string;
  depositMonths: (n: number) => string;
  tenancyClauses: (v: { rent: string; depositMonths: number }) => Clause[];
  mandateClauses: (v: { termMonths: number; ask: string }) => Clause[];
}

const EN: ContractCopy = {
  tenancyTitle: 'Residential Tenancy Agreement',
  mandateTitle: 'Agency Mandate',
  reference: (id) => `Contract ref ${id} · generated by PropVerify`,
  intro:
    'This agreement is made between the parties named below in respect of the property described, ' +
    'on the terms recorded in this document. It is executed by electronic signature: each party types ' +
    'their full name, and the platform records the name, the time and the originating IP address.',
  mandateIntro:
    'This mandate appoints the agent named below to market the property described, for the term ' +
    'stated, on the terms recorded here. It is executed by electronic signature: each party types ' +
    'their full name, and the platform records the name, the time and the originating IP address.',
  footer:
    'Generated by PropVerify. This document is stored privately and served only over short-lived, ' +
    'permission-checked links. Electronic signatures recorded on this document are accompanied by an ' +
    'immutable audit trail retained by the platform.',
  labels: {
    Property: 'Property',
    Address: 'Address',
    Rent: 'Rent',
    Term: 'Term',
    Deposit: 'Deposit',
    'Agreement date': 'Agreement date',
    "Owner's asking price": "Owner's asking price",
    Expires: 'Expires',
    'Mandate date': 'Mandate date',
    Tenant: 'Tenant',
    Landlord: 'Landlord',
    Owner: 'Owner',
    'Appointed agent': 'Appointed agent',
    'Landlord agent': 'Landlord agent',
    'Tenant agent': 'Tenant agent',
  },
  months: (n) => `${n} months`,
  depositMonths: (n) => `${n} month(s) rent`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Rent and payment',
      body: `The tenant shall pay rent of ${rent} for the term stated above, in the manner agreed between the parties. Receipts for any deposit or rent paid should be recorded in the deal room so both parties retain a copy.`,
    },
    {
      heading: 'Deposit',
      body: `A deposit equal to ${depositMonths} month(s) rent is held against damage beyond fair wear and tear, and against unpaid rent or utilities. It is returnable at the end of the tenancy less any properly evidenced deductions.`,
    },
    {
      heading: 'Condition of the property',
      body: 'The parties shall complete the move-in checklist in the deal room, with photographs, before occupation begins. That checklist is the agreed record of the condition of the property at the start of the tenancy.',
    },
    {
      heading: 'Utilities and charges',
      body: 'Unless the parties record otherwise in the deal room, the tenant is responsible for electricity, water and internet charges during the tenancy, and for transferring accounts into their name where required.',
    },
    {
      heading: 'Termination and renewal',
      body: 'Either party may give notice in accordance with the term agreed above. The platform will remind both parties before the term ends so that renewal or exit can be arranged in good time.',
    },
    {
      heading: 'Governing law',
      body: 'This agreement is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Appointment',
      body: `The owner appoints the agent to market the property for ${termMonths} months from the date of this mandate. The appointment lapses automatically on the expiry date above; it does not roll over, and the owner is free to appoint different agents afterwards.`,
    },
    {
      heading: "Owner's asking price",
      body: `The owner requires ${ask} for the property and receives that amount in full on completion. The platform fee and the agent's commission are added on top of it and are paid by the buyer, so neither reduces what the owner receives.`,
    },
    {
      heading: 'Anonymity and communication',
      body: 'The agent is not given the owner’s contact details, and the owner is not given the buyer’s. All communication runs through the platform, and a platform representative attends any stage that must happen in person. The agent shall not attempt to contact the owner outside the platform.',
    },
    {
      heading: 'Non-exclusivity',
      body: 'The owner may appoint more than one agent to the same property at the same time. Commission is earned by the agent whose introduction leads to the completed sale, as recorded by the platform.',
    },
    {
      heading: 'Conduct',
      body: 'The agent shall market the property accurately and only on the terms recorded here, shall not advertise it at a price other than the published list price, and shall not sub-instruct another agent without the owner’s written agreement.',
    },
    {
      heading: 'Governing law',
      body: 'This mandate is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
};

const TR: ContractCopy = {
  tenancyTitle: 'Konut Kira Sözleşmesi',
  mandateTitle: 'Yetki Sözleşmesi',
  reference: (id) => `Sözleşme referansı ${id} · PropVerify tarafından oluşturuldu`,
  intro:
    'Bu sözleşme, aşağıda adı geçen taraflar arasında, tanımlanan mülke ilişkin olarak ve bu belgede ' +
    'kayıtlı koşullarla yapılmıştır. Elektronik imza ile imzalanır: her taraf tam adını yazar; platform ' +
    'adı, zamanı ve bağlantının geldiği IP adresini kaydeder.',
  mandateIntro:
    'Bu yetki sözleşmesi, aşağıda adı geçen emlakçıyı, belirtilen süre boyunca ve burada kayıtlı ' +
    'koşullarla tanımlanan mülkü pazarlamak üzere yetkilendirir. Elektronik imza ile imzalanır: her taraf ' +
    'tam adını yazar; platform adı, zamanı ve bağlantının geldiği IP adresini kaydeder.',
  footer:
    'PropVerify tarafından oluşturulmuştur. Bu belge özel olarak saklanır ve yalnızca kısa ömürlü, ' +
    'yetki kontrollü bağlantılarla sunulur. Bu belgedeki elektronik imzalar, platformda saklanan ' +
    'değiştirilemez bir denetim kaydıyla birlikte tutulur.',
  labels: {
    Property: 'Mülk',
    Address: 'Adres',
    Rent: 'Kira',
    Term: 'Süre',
    Deposit: 'Depozito',
    'Agreement date': 'Sözleşme tarihi',
    "Owner's asking price": 'Mal sahibinin talep ettiği bedel',
    Expires: 'Bitiş',
    'Mandate date': 'Yetki tarihi',
    Tenant: 'Kiracı',
    Landlord: 'Mal sahibi',
    Owner: 'Mal sahibi',
    'Appointed agent': 'Yetkili emlakçı',
    'Landlord agent': 'Mal sahibi emlakçısı',
    'Tenant agent': 'Kiracı emlakçısı',
  },
  months: (n) => `${n} ay`,
  depositMonths: (n) => `${n} aylık kira`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Kira ve ödeme',
      body: `Kiracı, yukarıda belirtilen süre için ${rent} tutarında kirayı taraflar arasında kararlaştırılan şekilde ödeyecektir. Ödenen depozito veya kiraya ilişkin makbuzlar, her iki tarafın bir kopyayı saklayabilmesi için işlem odasına kaydedilmelidir.`,
    },
    {
      heading: 'Depozito',
      body: `${depositMonths} aylık kiraya eşit bir depozito; olağan kullanımın ötesindeki hasara, ödenmemiş kira ve faturalara karşılık tutulur. Kira süresi sonunda, usulüne uygun belgelenmiş kesintiler düşülerek iade edilir.`,
    },
    {
      heading: 'Mülkün durumu',
      body: 'Taraflar, oturum başlamadan önce işlem odasındaki giriş kontrol listesini fotoğraflarla birlikte tamamlayacaktır. Bu liste, kira başlangıcındaki mülk durumunun mutabık kalınan kaydıdır.',
    },
    {
      heading: 'Faturalar ve giderler',
      body: 'Taraflar işlem odasında aksini kaydetmedikçe, kira süresi boyunca elektrik, su ve internet giderleri kiracıya aittir; gerekli olduğunda abonelikleri kendi adına devretmek de kiracının sorumluluğundadır.',
    },
    {
      heading: 'Sona erme ve yenileme',
      body: 'Taraflardan her biri, yukarıda kararlaştırılan süreye uygun olarak bildirimde bulunabilir. Platform, yenileme veya çıkışın zamanında düzenlenebilmesi için süre bitmeden her iki tarafı hatırlatacaktır.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu sözleşme Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Yetkilendirme',
      body: `Mal sahibi, emlakçıyı bu yetki tarihinden itibaren ${termMonths} ay boyunca mülkü pazarlamak üzere yetkilendirir. Yetki, yukarıdaki bitiş tarihinde kendiliğinden sona erer; otomatik olarak uzamaz ve mal sahibi sonrasında başka emlakçılar yetkilendirmekte serbesttir.`,
    },
    {
      heading: 'Mal sahibinin talep ettiği bedel',
      body: `Mal sahibi mülk için ${ask} talep etmekte olup, tamamlanma anında bu tutarın tamamını alır. Platform ücreti ve emlakçı komisyonu bu tutarın üzerine eklenir ve alıcı tarafından ödenir; dolayısıyla hiçbiri mal sahibinin alacağı tutarı azaltmaz.`,
    },
    {
      heading: 'Gizlilik ve iletişim',
      body: 'Emlakçıya mal sahibinin iletişim bilgileri verilmez; mal sahibine de alıcının bilgileri verilmez. Tüm iletişim platform üzerinden yürür ve yüz yüze yapılması gereken aşamalarda bir platform temsilcisi hazır bulunur. Emlakçı, mal sahibine platform dışından ulaşmaya çalışmayacaktır.',
    },
    {
      heading: 'Münhasır olmama',
      body: 'Mal sahibi aynı mülk için aynı anda birden fazla emlakçı yetkilendirebilir. Komisyon, platform kayıtlarına göre tamamlanan satışa yol açan tanıştırmayı yapan emlakçı tarafından hak edilir.',
    },
    {
      heading: 'Davranış kuralları',
      body: 'Emlakçı, mülkü yalnızca burada kayıtlı koşullarla ve doğru biçimde pazarlayacak, yayımlanan liste fiyatından farklı bir fiyatla ilan vermeyecek ve mal sahibinin yazılı onayı olmadan başka bir emlakçıya alt yetki vermeyecektir.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu yetki sözleşmesi Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
};

const RU: ContractCopy = {
  tenancyTitle: 'Договор аренды жилого помещения',
  mandateTitle: 'Агентский мандат',
  reference: (id) => `Номер договора ${id} · сформирован PropVerify`,
  intro:
    'Настоящий договор заключён между указанными ниже сторонами в отношении описанного объекта на ' +
    'условиях, зафиксированных в этом документе. Он подписывается электронной подписью: каждая сторона ' +
    'вводит своё полное имя, а платформа фиксирует имя, время и IP-адрес подключения.',
  mandateIntro:
    'Настоящий мандат уполномочивает указанного ниже агента заниматься продажей описанного объекта в ' +
    'течение указанного срока на зафиксированных здесь условиях. Он подписывается электронной подписью: ' +
    'каждая сторона вводит своё полное имя, а платформа фиксирует имя, время и IP-адрес подключения.',
  footer:
    'Сформировано PropVerify. Документ хранится приватно и выдаётся только по коротко живущим ссылкам с ' +
    'проверкой прав. Электронные подписи на этом документе сопровождаются неизменяемым журналом аудита, ' +
    'который хранит платформа.',
  labels: {
    Property: 'Объект',
    Address: 'Адрес',
    Rent: 'Арендная плата',
    Term: 'Срок',
    Deposit: 'Депозит',
    'Agreement date': 'Дата договора',
    "Owner's asking price": 'Запрашиваемая цена собственника',
    Expires: 'Действует до',
    'Mandate date': 'Дата мандата',
    Tenant: 'Арендатор',
    Landlord: 'Арендодатель',
    Owner: 'Собственник',
    'Appointed agent': 'Назначенный агент',
    'Landlord agent': 'Агент арендодателя',
    'Tenant agent': 'Агент арендатора',
  },
  months: (n) => `${n} мес.`,
  depositMonths: (n) => `аренда за ${n} мес.`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Арендная плата и порядок оплаты',
      body: `Арендатор уплачивает арендную плату в размере ${rent} за указанный выше срок в порядке, согласованном сторонами. Квитанции об уплате депозита или аренды следует загружать в комнату сделки, чтобы копия оставалась у обеих сторон.`,
    },
    {
      heading: 'Депозит',
      body: `Депозит в размере арендной платы за ${depositMonths} мес. удерживается в обеспечение ущерба сверх обычного износа, а также неоплаченной аренды и коммунальных услуг. Он возвращается по окончании аренды за вычетом документально подтверждённых удержаний.`,
    },
    {
      heading: 'Состояние объекта',
      body: 'До заселения стороны совместно заполняют контрольный лист приёмки в комнате сделки, приложив фотографии. Этот лист является согласованной фиксацией состояния объекта на начало аренды.',
    },
    {
      heading: 'Коммунальные услуги и расходы',
      body: 'Если стороны не зафиксировали иное в комнате сделки, арендатор несёт расходы на электричество, воду и интернет в течение аренды и, где это требуется, переоформляет договоры на своё имя.',
    },
    {
      heading: 'Прекращение и продление',
      body: 'Любая из сторон вправе направить уведомление в соответствии с согласованным выше сроком. Платформа напомнит обеим сторонам до окончания срока, чтобы продление или выезд можно было организовать заранее.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий договор регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Назначение',
      body: `Собственник поручает агенту заниматься продажей объекта в течение ${termMonths} мес. с даты настоящего мандата. Полномочия прекращаются автоматически в указанную выше дату, не продлеваются сами собой, и после этого собственник вправе назначить других агентов.`,
    },
    {
      heading: 'Запрашиваемая цена собственника',
      body: `Собственник запрашивает за объект ${ask} и получает эту сумму полностью при завершении сделки. Комиссия платформы и вознаграждение агента добавляются сверх неё и оплачиваются покупателем, поэтому ни одно из них не уменьшает сумму, получаемую собственником.`,
    },
    {
      heading: 'Анонимность и связь',
      body: 'Агенту не передаются контактные данные собственника, а собственнику — данные покупателя. Всё общение идёт через платформу, а на этапах, которые должны проходить лично, присутствует представитель платформы. Агент не вправе пытаться связаться с собственником вне платформы.',
    },
    {
      heading: 'Отсутствие исключительности',
      body: 'Собственник вправе одновременно назначить нескольких агентов на один объект. Вознаграждение получает тот агент, чьё представление привело к завершённой сделке, согласно записям платформы.',
    },
    {
      heading: 'Правила поведения',
      body: 'Агент обязан представлять объект достоверно и только на зафиксированных здесь условиях, не размещать объявления по цене, отличной от опубликованной, и не передавать поручение другому агенту без письменного согласия собственника.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий мандат регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
};

const COPY: Record<ContractLocale, ContractCopy> = { en: EN, tr: TR, ru: RU };

export const contractCopy = (locale: ContractLocale): ContractCopy => COPY[locale] ?? EN;
