/**
 * Contract wording, per locale (Plan §7, §6.2).
 *
 * Kept out of the service because it is prose a lawyer may want to review and
 * revise without touching generation logic, and because a clause list is the
 * part of a contract that must be diffable.
 *
 * **Farsi maps to English on purpose.** The embedded font has Arabic glyphs,
 * but pdf-lib has no shaping engine, so Farsi would render as disconnected
 * letters in the wrong order — worse than English in a document someone signs.
 * `NOT_IN_YOUR_LANGUAGE` says so in the document itself rather than leaving a
 * reader to wonder. See the note in pdf.service.ts.
 *
 * Dropped as scope on 2026-09-03 (Plan §0 Change Log), so this is the settled
 * behaviour rather than a gap awaiting a shaping pass — which is why the notice
 * below no longer says a Farsi version is coming.
 */
export type ContractLocale = 'en' | 'tr' | 'ru';

/** The locales a contract can actually be rendered in. */
export const CONTRACT_LOCALES: ContractLocale[] = ['en', 'tr', 'ru'];

export function contractLocale(userLocale: string | null | undefined): ContractLocale {
  return (CONTRACT_LOCALES as string[]).includes(userLocale ?? '')
    ? (userLocale as ContractLocale)
    : 'en';
}

/**
 * Shown when the reader's own language is not one a contract can render in.
 *
 * Written in English rather than the reader's language, which looks backwards
 * until you notice the circularity: the reason for the notice is that we cannot
 * draw that script, so a notice in it would be stripped to nothing. Naming the
 * language in English is the most that can actually reach the page.
 */
export const NOT_IN_YOUR_LANGUAGE: Record<string, string> = {
  fa: 'NOTE: This document is issued in English. A Farsi version of this contract is not available — please obtain a certified translation before signing if you need one.',
};

interface Clause {
  heading: string;
  body: string;
}

export interface ContractCopy {
  tenancyTitle: string;
  mandateTitle: string;
  reference: (id: string) => string;
  intro: string;
  mandateIntro: string;
  footer: string;
  labels: Record<string, string>;
  /** Units belong with the number and have to translate with it. */
  months: (n: number) => string;
  depositMonths: (n: number) => string;
  tenancyClauses: (v: { rent: string; depositMonths: number }) => Clause[];
  mandateClauses: (v: { termMonths: number; ask: string }) => Clause[];
  saleClauses: (v: { price: string; deedType: string }) => Clause[];
  offplanClauses: (v: { price: string; deedType: string; delivery: string }) => Clause[];
  saleTitle: string;
  offplanTitle: string;
  saleIntro: string;
  offplanIntro: string;
  /** Deed types are legal categories, so they are named, not translated away. */
  deedTypes: Record<string, string>;
}

const EN: ContractCopy = {
  tenancyTitle: 'Residential Tenancy Agreement',
  mandateTitle: 'Agency Mandate',
  reference: (id) => `Contract ref ${id} · generated by PropVerify`,
  intro:
    'This agreement is made between the parties named below in respect of the property described, ' +
    'on the terms recorded in this document. It is executed by electronic signature: each party types ' +
    'their full name, and the platform records the name, the time and the originating IP address.',
  mandateIntro:
    'This mandate appoints the agent named below to market the property described, for the term ' +
    'stated, on the terms recorded here. It is executed by electronic signature: each party types ' +
    'their full name, and the platform records the name, the time and the originating IP address.',
  footer:
    'Generated by PropVerify. This document is stored privately and served only over short-lived, ' +
    'permission-checked links. Electronic signatures recorded on this document are accompanied by an ' +
    'immutable audit trail retained by the platform.',
  labels: {
    Property: 'Property',
    Address: 'Address',
    Rent: 'Rent',
    Term: 'Term',
    Deposit: 'Deposit',
    'Agreement date': 'Agreement date',
    "Owner's asking price": "Owner's asking price",
    Expires: 'Expires',
    'Mandate date': 'Mandate date',
    Tenant: 'Tenant',
    Landlord: 'Landlord',
    Owner: 'Owner',
    'Appointed agent': 'Appointed agent',
    'Landlord agent': 'Landlord agent',
    'Tenant agent': 'Tenant agent',
    Price: 'Price',
    Deed: 'Title deed',
    Delivery: 'Delivery',
    'On completion': 'On completion',
    Buyer: 'Buyer',
    Seller: 'Seller',
    'Seller agent': 'Seller agent',
    'Buyer agent': 'Buyer agent',
  },
  months: (n) => `${n} months`,
  depositMonths: (n) => `${n} month(s) rent`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Rent and payment',
      body: `The tenant shall pay rent of ${rent} for the term stated above, in the manner agreed between the parties. Receipts for any deposit or rent paid should be recorded in the deal room so both parties retain a copy.`,
    },
    {
      heading: 'Deposit',
      body: `A deposit equal to ${depositMonths} month(s) rent is held against damage beyond fair wear and tear, and against unpaid rent or utilities. It is returnable at the end of the tenancy less any properly evidenced deductions.`,
    },
    {
      heading: 'Condition of the property',
      body: 'The parties shall complete the move-in checklist in the deal room, with photographs, before occupation begins. That checklist is the agreed record of the condition of the property at the start of the tenancy.',
    },
    {
      heading: 'Utilities and charges',
      body: 'Unless the parties record otherwise in the deal room, the tenant is responsible for electricity, water and internet charges during the tenancy, and for transferring accounts into their name where required.',
    },
    {
      heading: 'Termination and renewal',
      body: 'Either party may give notice in accordance with the term agreed above. The platform will remind both parties before the term ends so that renewal or exit can be arranged in good time.',
    },
    {
      heading: 'Governing law',
      body: 'This agreement is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
  saleTitle: 'Sale and Purchase Agreement',
  offplanTitle: 'Off-Plan Sale and Purchase Agreement',
  saleIntro:
    'This agreement records the sale of the property described below by the seller to the buyer, at ' +
    'the price and on the terms stated. It is executed by electronic signature: each party types their ' +
    'full name, and the platform records the name, the time and the originating IP address.',
  offplanIntro:
    'This agreement records the sale of a property still under construction, described below, by the ' +
    'developer to the buyer at the price and on the terms stated, for delivery on the date given. It is ' +
    'executed by electronic signature: each party types their full name, and the platform records the ' +
    'name, the time and the originating IP address.',
  deedTypes: {
    turkish: 'Turkish title (pre-1974)',
    exchange: 'Exchange title (Eşdeğer)',
    allocation: 'Allocation title (Tahsis)',
    foreign: 'Foreign title',
    na: 'Not stated',
  },
  saleClauses: ({ price, deedType }) => [
    {
      heading: 'Price and payment',
      body: `The agreed price is ${price}. The buyer pays a deposit on signature and the balance on completion, in the manner recorded in the deal room. Every payment should be receipted there so both parties keep the same record.`,
    },
    {
      heading: 'Title and deed type',
      body: `The property is sold with ${deedType}. The seller confirms the title is theirs to sell and is free of undisclosed charges. The deed type materially affects what a buyer receives, and independent legal advice on it is strongly recommended before completion.`,
    },
    {
      heading: 'Purchase permit',
      body: 'Buyers who are not citizens require a purchase permit before title can be transferred. The buyer is responsible for applying; the seller shall provide the documents the application needs. Completion is conditional on the permit where one is required.',
    },
    {
      heading: 'Transfer and completion',
      body: 'On completion the balance is paid, the property is handed over, and the parties attend the Land Registry to transfer the title. A platform representative attends the handover. Possession passes on completion, not on signature.',
    },
    {
      heading: 'Withdrawal and default',
      body: 'If the buyer withdraws without a contractual reason, the deposit may be forfeited. If the seller withdraws, the deposit is returned. Neither is a penalty for a failure of the permit or the title search, where the deposit is returned in full.',
    },
    {
      heading: 'Governing law',
      body: 'This agreement is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
  offplanClauses: ({ price, deedType, delivery }) => [
    {
      heading: 'Price and payment schedule',
      body: `The agreed price is ${price}, payable to the schedule recorded in the deal room: a deposit on signature, stage payments during construction, and the balance on delivery. Each payment should be receipted in the deal room.`,
    },
    {
      heading: 'Delivery',
      body: `The developer shall deliver the unit by ${delivery}. Where delivery is delayed, the developer shall notify the buyer and give a revised date. Payments tied to delivery fall due on actual delivery, not on the original date.`,
    },
    {
      heading: 'Title and deed type',
      body: `Title is to be transferred with ${deedType} once the unit is complete and the permit, where required, is granted. Until transfer the buyer's interest should be protected by registering the contract, and independent legal advice on this is strongly recommended.`,
    },
    {
      heading: 'Specification and snagging',
      body: 'The unit shall be delivered to the specification recorded in the deal room. On handover the parties complete a snagging list together; the developer shall remedy the listed items within a reasonable period.',
    },
    {
      heading: 'Purchase permit',
      body: 'Buyers who are not citizens require a purchase permit before title can be transferred. The buyer is responsible for applying; the developer shall provide the documents the application needs.',
    },
    {
      heading: 'Governing law',
      body: 'This agreement is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Appointment',
      body: `The owner appoints the agent to market the property for ${termMonths} months from the date of this mandate. The appointment lapses automatically on the expiry date above; it does not roll over, and the owner is free to appoint different agents afterwards.`,
    },
    {
      heading: "Owner's asking price",
      body: `The owner requires ${ask} for the property and receives that amount in full on completion. The platform fee and the agent's commission are added on top of it and are paid by the buyer, so neither reduces what the owner receives.`,
    },
    {
      heading: 'Anonymity and communication',
      body: 'The agent is not given the owner’s contact details, and the owner is not given the buyer’s. All communication runs through the platform, and a platform representative attends any stage that must happen in person. The agent shall not attempt to contact the owner outside the platform.',
    },
    {
      heading: 'Non-exclusivity',
      body: 'The owner may appoint more than one agent to the same property at the same time. Commission is earned by the agent whose introduction leads to the completed sale, as recorded by the platform.',
    },
    {
      heading: 'Conduct',
      body: 'The agent shall market the property accurately and only on the terms recorded here, shall not advertise it at a price other than the published list price, and shall not sub-instruct another agent without the owner’s written agreement.',
    },
    {
      heading: 'Governing law',
      body: 'This mandate is governed by the law of the Turkish Republic of Northern Cyprus. It records the commercial terms agreed between the parties and does not replace independent legal advice.',
    },
  ],
};

const TR: ContractCopy = {
  tenancyTitle: 'Konut Kira Sözleşmesi',
  mandateTitle: 'Yetki Sözleşmesi',
  reference: (id) => `Sözleşme referansı ${id} · PropVerify tarafından oluşturuldu`,
  intro:
    'Bu sözleşme, aşağıda adı geçen taraflar arasında, tanımlanan mülke ilişkin olarak ve bu belgede ' +
    'kayıtlı koşullarla yapılmıştır. Elektronik imza ile imzalanır: her taraf tam adını yazar; platform ' +
    'adı, zamanı ve bağlantının geldiği IP adresini kaydeder.',
  mandateIntro:
    'Bu yetki sözleşmesi, aşağıda adı geçen emlakçıyı, belirtilen süre boyunca ve burada kayıtlı ' +
    'koşullarla tanımlanan mülkü pazarlamak üzere yetkilendirir. Elektronik imza ile imzalanır: her taraf ' +
    'tam adını yazar; platform adı, zamanı ve bağlantının geldiği IP adresini kaydeder.',
  footer:
    'PropVerify tarafından oluşturulmuştur. Bu belge özel olarak saklanır ve yalnızca kısa ömürlü, ' +
    'yetki kontrollü bağlantılarla sunulur. Bu belgedeki elektronik imzalar, platformda saklanan ' +
    'değiştirilemez bir denetim kaydıyla birlikte tutulur.',
  labels: {
    Property: 'Mülk',
    Address: 'Adres',
    Rent: 'Kira',
    Term: 'Süre',
    Deposit: 'Depozito',
    'Agreement date': 'Sözleşme tarihi',
    "Owner's asking price": 'Mal sahibinin talep ettiği bedel',
    Expires: 'Bitiş',
    'Mandate date': 'Yetki tarihi',
    Tenant: 'Kiracı',
    Landlord: 'Mal sahibi',
    Owner: 'Mal sahibi',
    'Appointed agent': 'Yetkili emlakçı',
    'Landlord agent': 'Mal sahibi emlakçısı',
    'Tenant agent': 'Kiracı emlakçısı',
    Price: 'Bedel',
    Deed: 'Tapu',
    Delivery: 'Teslim',
    'On completion': 'Tamamlamada',
    Buyer: 'Alıcı',
    Seller: 'Satıcı',
    'Seller agent': 'Satıcı emlakçısı',
    'Buyer agent': 'Alıcı emlakçısı',
  },
  months: (n) => `${n} ay`,
  depositMonths: (n) => `${n} aylık kira`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Kira ve ödeme',
      body: `Kiracı, yukarıda belirtilen süre için ${rent} tutarında kirayı taraflar arasında kararlaştırılan şekilde ödeyecektir. Ödenen depozito veya kiraya ilişkin makbuzlar, her iki tarafın bir kopyayı saklayabilmesi için işlem odasına kaydedilmelidir.`,
    },
    {
      heading: 'Depozito',
      body: `${depositMonths} aylık kiraya eşit bir depozito; olağan kullanımın ötesindeki hasara, ödenmemiş kira ve faturalara karşılık tutulur. Kira süresi sonunda, usulüne uygun belgelenmiş kesintiler düşülerek iade edilir.`,
    },
    {
      heading: 'Mülkün durumu',
      body: 'Taraflar, oturum başlamadan önce işlem odasındaki giriş kontrol listesini fotoğraflarla birlikte tamamlayacaktır. Bu liste, kira başlangıcındaki mülk durumunun mutabık kalınan kaydıdır.',
    },
    {
      heading: 'Faturalar ve giderler',
      body: 'Taraflar işlem odasında aksini kaydetmedikçe, kira süresi boyunca elektrik, su ve internet giderleri kiracıya aittir; gerekli olduğunda abonelikleri kendi adına devretmek de kiracının sorumluluğundadır.',
    },
    {
      heading: 'Sona erme ve yenileme',
      body: 'Taraflardan her biri, yukarıda kararlaştırılan süreye uygun olarak bildirimde bulunabilir. Platform, yenileme veya çıkışın zamanında düzenlenebilmesi için süre bitmeden her iki tarafı hatırlatacaktır.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu sözleşme Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
  saleTitle: 'Satış Sözleşmesi',
  offplanTitle: 'Proje Aşamasında Satış Sözleşmesi',
  saleIntro:
    'Bu sözleşme, aşağıda tanımlanan mülkün satıcı tarafından alıcıya, belirtilen bedel ve koşullarla ' +
    'satışını kayıt altına alır. Elektronik imza ile imzalanır: her taraf tam adını yazar; platform adı, ' +
    'zamanı ve bağlantının geldiği IP adresini kaydeder.',
  offplanIntro:
    'Bu sözleşme, aşağıda tanımlanan ve hâlâ inşa hâlinde olan bir mülkün, geliştirici tarafından ' +
    'alıcıya belirtilen bedel ve koşullarla, verilen teslim tarihinde teslim edilmek üzere satışını ' +
    'kayıt altına alır. Elektronik imza ile imzalanır: her taraf tam adını yazar; platform adı, zamanı ' +
    've bağlantının geldiği IP adresini kaydeder.',
  deedTypes: {
    turkish: 'Türk koçanı (1974 öncesi)',
    exchange: 'Eşdeğer koçan',
    allocation: 'Tahsis koçanı',
    foreign: 'Yabancı koçan',
    na: 'Belirtilmemiş',
  },
  saleClauses: ({ price, deedType }) => [
    {
      heading: 'Bedel ve ödeme',
      body: `Kararlaştırılan bedel ${price} tutarındadır. Alıcı, imza sırasında bir depozito, tamamlanmada ise bakiyeyi işlem odasında kayıtlı şekilde öder. Her ödeme, iki tarafın da aynı kaydı tutabilmesi için orada makbuzlandırılmalıdır.`,
    },
    {
      heading: 'Tapu ve koçan türü',
      body: `Mülk ${deedType} ile satılmaktadır. Satıcı, tapunun satmaya yetkili olduğu kendi mülkiyetinde bulunduğunu ve açıklanmamış takyidat bulunmadığını beyan eder. Koçan türü alıcının elde ettiği hakkı esaslı biçimde etkiler; tamamlamadan önce bu konuda bağımsız hukuki danışmanlık alınması önemle tavsiye edilir.`,
    },
    {
      heading: 'Satın alma izni',
      body: 'Vatandaş olmayan alıcıların, tapu devri öncesinde satın alma izni alması gerekir. Başvuru alıcının sorumluluğundadır; satıcı, başvurunun gerektirdiği belgeleri sağlar. İzin gereken hâllerde tamamlama bu izne bağlıdır.',
    },
    {
      heading: 'Devir ve tamamlama',
      body: 'Tamamlamada bakiye ödenir, mülk teslim edilir ve taraflar tapu devri için Tapu Dairesine giderler. Teslimde bir platform temsilcisi hazır bulunur. Zilyetlik imzada değil, tamamlamada geçer.',
    },
    {
      heading: 'Cayma ve temerrüt',
      body: 'Alıcı sözleşmeye dayalı bir sebep olmaksızın cayarsa depozito irat kaydedilebilir. Satıcı cayarsa depozito iade edilir. İznin veya tapu araştırmasının olumsuz sonuçlanması bunlardan sayılmaz; bu hâllerde depozito tam olarak iade edilir.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu sözleşme Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
  offplanClauses: ({ price, deedType, delivery }) => [
    {
      heading: 'Bedel ve ödeme planı',
      body: `Kararlaştırılan bedel ${price} tutarında olup işlem odasında kayıtlı plana göre ödenir: imzada depozito, inşaat boyunca ara ödemeler ve teslimde bakiye. Her ödeme işlem odasında makbuzlandırılmalıdır.`,
    },
    {
      heading: 'Teslim',
      body: `Geliştirici, birimi ${delivery} tarihine kadar teslim eder. Teslimin gecikmesi hâlinde geliştirici alıcıya bildirimde bulunur ve revize bir tarih verir. Teslime bağlı ödemeler, ilk tarihte değil, fiilî teslimde muaccel olur.`,
    },
    {
      heading: 'Tapu ve koçan türü',
      body: `Tapu, birim tamamlandığında ve gerekli olduğu hâllerde izin verildiğinde ${deedType} ile devredilecektir. Devre kadar alıcının hakkı sözleşmenin tapuya şerhi ile korunmalıdır; bu konuda bağımsız hukuki danışmanlık alınması önemle tavsiye edilir.`,
    },
    {
      heading: 'Teknik şartname ve eksik listesi',
      body: 'Birim, işlem odasında kayıtlı teknik şartnameye uygun olarak teslim edilir. Teslimde taraflar birlikte bir eksik listesi düzenler; geliştirici listedeki işleri makul bir süre içinde giderir.',
    },
    {
      heading: 'Satın alma izni',
      body: 'Vatandaş olmayan alıcıların, tapu devri öncesinde satın alma izni alması gerekir. Başvuru alıcının sorumluluğundadır; geliştirici, başvurunun gerektirdiği belgeleri sağlar.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu sözleşme Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Yetkilendirme',
      body: `Mal sahibi, emlakçıyı bu yetki tarihinden itibaren ${termMonths} ay boyunca mülkü pazarlamak üzere yetkilendirir. Yetki, yukarıdaki bitiş tarihinde kendiliğinden sona erer; otomatik olarak uzamaz ve mal sahibi sonrasında başka emlakçılar yetkilendirmekte serbesttir.`,
    },
    {
      heading: 'Mal sahibinin talep ettiği bedel',
      body: `Mal sahibi mülk için ${ask} talep etmekte olup, tamamlanma anında bu tutarın tamamını alır. Platform ücreti ve emlakçı komisyonu bu tutarın üzerine eklenir ve alıcı tarafından ödenir; dolayısıyla hiçbiri mal sahibinin alacağı tutarı azaltmaz.`,
    },
    {
      heading: 'Gizlilik ve iletişim',
      body: 'Emlakçıya mal sahibinin iletişim bilgileri verilmez; mal sahibine de alıcının bilgileri verilmez. Tüm iletişim platform üzerinden yürür ve yüz yüze yapılması gereken aşamalarda bir platform temsilcisi hazır bulunur. Emlakçı, mal sahibine platform dışından ulaşmaya çalışmayacaktır.',
    },
    {
      heading: 'Münhasır olmama',
      body: 'Mal sahibi aynı mülk için aynı anda birden fazla emlakçı yetkilendirebilir. Komisyon, platform kayıtlarına göre tamamlanan satışa yol açan tanıştırmayı yapan emlakçı tarafından hak edilir.',
    },
    {
      heading: 'Davranış kuralları',
      body: 'Emlakçı, mülkü yalnızca burada kayıtlı koşullarla ve doğru biçimde pazarlayacak, yayımlanan liste fiyatından farklı bir fiyatla ilan vermeyecek ve mal sahibinin yazılı onayı olmadan başka bir emlakçıya alt yetki vermeyecektir.',
    },
    {
      heading: 'Uygulanacak hukuk',
      body: 'Bu yetki sözleşmesi Kuzey Kıbrıs Türk Cumhuriyeti hukukuna tabidir. Taraflar arasında kararlaştırılan ticari koşulları kaydeder ve bağımsız hukuki danışmanlığın yerine geçmez.',
    },
  ],
};

const RU: ContractCopy = {
  tenancyTitle: 'Договор аренды жилого помещения',
  mandateTitle: 'Агентский мандат',
  reference: (id) => `Номер договора ${id} · сформирован PropVerify`,
  intro:
    'Настоящий договор заключён между указанными ниже сторонами в отношении описанного объекта на ' +
    'условиях, зафиксированных в этом документе. Он подписывается электронной подписью: каждая сторона ' +
    'вводит своё полное имя, а платформа фиксирует имя, время и IP-адрес подключения.',
  mandateIntro:
    'Настоящий мандат уполномочивает указанного ниже агента заниматься продажей описанного объекта в ' +
    'течение указанного срока на зафиксированных здесь условиях. Он подписывается электронной подписью: ' +
    'каждая сторона вводит своё полное имя, а платформа фиксирует имя, время и IP-адрес подключения.',
  footer:
    'Сформировано PropVerify. Документ хранится приватно и выдаётся только по коротко живущим ссылкам с ' +
    'проверкой прав. Электронные подписи на этом документе сопровождаются неизменяемым журналом аудита, ' +
    'который хранит платформа.',
  labels: {
    Property: 'Объект',
    Address: 'Адрес',
    Rent: 'Арендная плата',
    Term: 'Срок',
    Deposit: 'Депозит',
    'Agreement date': 'Дата договора',
    "Owner's asking price": 'Запрашиваемая цена собственника',
    Expires: 'Действует до',
    'Mandate date': 'Дата мандата',
    Tenant: 'Арендатор',
    Landlord: 'Арендодатель',
    Owner: 'Собственник',
    'Appointed agent': 'Назначенный агент',
    'Landlord agent': 'Агент арендодателя',
    'Tenant agent': 'Агент арендатора',
    Price: 'Цена',
    Deed: 'Документ о собственности',
    Delivery: 'Сдача',
    'On completion': 'При завершении',
    Buyer: 'Покупатель',
    Seller: 'Продавец',
    'Seller agent': 'Агент продавца',
    'Buyer agent': 'Агент покупателя',
  },
  months: (n) => `${n} мес.`,
  depositMonths: (n) => `аренда за ${n} мес.`,
  tenancyClauses: ({ rent, depositMonths }) => [
    {
      heading: 'Арендная плата и порядок оплаты',
      body: `Арендатор уплачивает арендную плату в размере ${rent} за указанный выше срок в порядке, согласованном сторонами. Квитанции об уплате депозита или аренды следует загружать в комнату сделки, чтобы копия оставалась у обеих сторон.`,
    },
    {
      heading: 'Депозит',
      body: `Депозит в размере арендной платы за ${depositMonths} мес. удерживается в обеспечение ущерба сверх обычного износа, а также неоплаченной аренды и коммунальных услуг. Он возвращается по окончании аренды за вычетом документально подтверждённых удержаний.`,
    },
    {
      heading: 'Состояние объекта',
      body: 'До заселения стороны совместно заполняют контрольный лист приёмки в комнате сделки, приложив фотографии. Этот лист является согласованной фиксацией состояния объекта на начало аренды.',
    },
    {
      heading: 'Коммунальные услуги и расходы',
      body: 'Если стороны не зафиксировали иное в комнате сделки, арендатор несёт расходы на электричество, воду и интернет в течение аренды и, где это требуется, переоформляет договоры на своё имя.',
    },
    {
      heading: 'Прекращение и продление',
      body: 'Любая из сторон вправе направить уведомление в соответствии с согласованным выше сроком. Платформа напомнит обеим сторонам до окончания срока, чтобы продление или выезд можно было организовать заранее.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий договор регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
  saleTitle: 'Договор купли-продажи',
  offplanTitle: 'Договор купли-продажи на стадии строительства',
  saleIntro:
    'Настоящий договор фиксирует продажу описанного ниже объекта продавцом покупателю по указанной цене ' +
    'и на указанных условиях. Он подписывается электронной подписью: каждая сторона вводит своё полное ' +
    'имя, а платформа фиксирует имя, время и IP-адрес подключения.',
  offplanIntro:
    'Настоящий договор фиксирует продажу описанного ниже объекта, находящегося в стадии строительства, ' +
    'застройщиком покупателю по указанной цене и на указанных условиях, со сдачей в указанную дату. Он ' +
    'подписывается электронной подписью: каждая сторона вводит своё полное имя, а платформа фиксирует ' +
    'имя, время и IP-адрес подключения.',
  deedTypes: {
    turkish: 'Турецкий титул (до 1974 г.)',
    exchange: 'Обменный титул (Eşdeğer)',
    allocation: 'Выделенный титул (Tahsis)',
    foreign: 'Иностранный титул',
    na: 'Не указан',
  },
  saleClauses: ({ price, deedType }) => [
    {
      heading: 'Цена и порядок оплаты',
      body: `Согласованная цена составляет ${price}. Покупатель вносит задаток при подписании и остаток при завершении сделки в порядке, зафиксированном в комнате сделки. По каждому платежу следует загружать квитанцию, чтобы у обеих сторон была одна и та же запись.`,
    },
    {
      heading: 'Титул и тип документа',
      body: `Объект продаётся с документом «${deedType}». Продавец подтверждает, что титул принадлежит ему и свободен от нераскрытых обременений. Тип документа существенно влияет на то, что получает покупатель, поэтому до завершения сделки настоятельно рекомендуется независимая юридическая консультация по нему.`,
    },
    {
      heading: 'Разрешение на покупку',
      body: 'Покупателям, не являющимся гражданами, до перехода титула требуется разрешение на покупку. Подача заявления — обязанность покупателя; продавец предоставляет необходимые для заявления документы. Там, где разрешение требуется, завершение сделки обусловлено его получением.',
    },
    {
      heading: 'Переход права и завершение',
      body: 'При завершении уплачивается остаток, объект передаётся, и стороны обращаются в Земельный кадастр для перехода титула. На передаче присутствует представитель платформы. Владение переходит при завершении, а не при подписании.',
    },
    {
      heading: 'Отказ и нарушение',
      body: 'Если покупатель отказывается без предусмотренного договором основания, задаток может быть удержан. Если отказывается продавец, задаток возвращается. Это не относится к отказу в разрешении или к результатам проверки титула — в таких случаях задаток возвращается полностью.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий договор регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
  offplanClauses: ({ price, deedType, delivery }) => [
    {
      heading: 'Цена и график платежей',
      body: `Согласованная цена составляет ${price} и уплачивается по графику, зафиксированному в комнате сделки: задаток при подписании, промежуточные платежи в ходе строительства и остаток при сдаче. По каждому платежу следует загружать квитанцию.`,
    },
    {
      heading: 'Сдача объекта',
      body: `Застройщик передаёт объект не позднее ${delivery}. При задержке застройщик уведомляет покупателя и сообщает новую дату. Платежи, привязанные к сдаче, наступают по факту передачи, а не по первоначальной дате.`,
    },
    {
      heading: 'Титул и тип документа',
      body: `Титул передаётся с документом «${deedType}» после завершения строительства и получения разрешения, если оно требуется. До перехода титула интерес покупателя следует защитить регистрацией договора; по этому вопросу настоятельно рекомендуется независимая юридическая консультация.`,
    },
    {
      heading: 'Спецификация и приёмка',
      body: 'Объект передаётся в соответствии со спецификацией, зафиксированной в комнате сделки. При передаче стороны совместно составляют дефектную ведомость; застройщик устраняет перечисленные замечания в разумный срок.',
    },
    {
      heading: 'Разрешение на покупку',
      body: 'Покупателям, не являющимся гражданами, до перехода титула требуется разрешение на покупку. Подача заявления — обязанность покупателя; застройщик предоставляет необходимые для заявления документы.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий договор регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
  mandateClauses: ({ termMonths, ask }) => [
    {
      heading: 'Назначение',
      body: `Собственник поручает агенту заниматься продажей объекта в течение ${termMonths} мес. с даты настоящего мандата. Полномочия прекращаются автоматически в указанную выше дату, не продлеваются сами собой, и после этого собственник вправе назначить других агентов.`,
    },
    {
      heading: 'Запрашиваемая цена собственника',
      body: `Собственник запрашивает за объект ${ask} и получает эту сумму полностью при завершении сделки. Комиссия платформы и вознаграждение агента добавляются сверх неё и оплачиваются покупателем, поэтому ни одно из них не уменьшает сумму, получаемую собственником.`,
    },
    {
      heading: 'Анонимность и связь',
      body: 'Агенту не передаются контактные данные собственника, а собственнику — данные покупателя. Всё общение идёт через платформу, а на этапах, которые должны проходить лично, присутствует представитель платформы. Агент не вправе пытаться связаться с собственником вне платформы.',
    },
    {
      heading: 'Отсутствие исключительности',
      body: 'Собственник вправе одновременно назначить нескольких агентов на один объект. Вознаграждение получает тот агент, чьё представление привело к завершённой сделке, согласно записям платформы.',
    },
    {
      heading: 'Правила поведения',
      body: 'Агент обязан представлять объект достоверно и только на зафиксированных здесь условиях, не размещать объявления по цене, отличной от опубликованной, и не передавать поручение другому агенту без письменного согласия собственника.',
    },
    {
      heading: 'Применимое право',
      body: 'Настоящий мандат регулируется правом Турецкой Республики Северного Кипра. Он фиксирует коммерческие условия, согласованные сторонами, и не заменяет независимую юридическую консультацию.',
    },
  ],
};

const COPY: Record<ContractLocale, ContractCopy> = { en: EN, tr: TR, ru: RU };

export const contractCopy = (locale: ContractLocale): ContractCopy => COPY[locale] ?? EN;
